
### Common Vars
ansible_ssh_user: ec2-user
remote_user: ec2-user

lab_tag: "1.0.0"

subdomain_base_short: "{{guid}}"
subdomain_base: "{{subdomain_base_short}}.openshift3roadshow.com"

rhel_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-ose-{{repo_version}}-rpms

use_subscription_manager: true
use_opentlc_repos: false

## NFS Server settings
nfs_vg: nfsvg
nfs_pvs: /dev/xvdb
nfs_export_path: /srv/nfs

nfs_shares:
  - user-vols

workshop_shares:
  - postgres
  - nexus
  - gitlab-data
  - gitlab-etc
  - redis

user_vols: 100
user_vols_size: 5Gi

cache_images:
  - "openshift3/logging-elasticsearch"
  - "openshift3/logging-deployer"
  - "openshift3/metrics-cassandra"
  - "openshift3/metrics-hawkular-metrics"
  - "openshift3/metrics-heapster"
  - "openshift3/logging-auth-proxy"
  - "openshift3/ose-haproxy-router"
  - "openshift3/ose-deployer"
  - "openshift3/logging-deployment"
  - "openshift3/logging-fluentd"
  - "openshift3/logging-kibana"
  - "openshift3/metrics-deployer"
  - "openshift3/ose-pod"
  - "openshift3/ose-docker-registry"
  - "openshift3/registry-console"
  - "openshift3/logging-curator"
  - "openshiftdemos/parksmap:0.4"
  - "openshift3/jenkins-1-rhel7"
  - "jorgemoralespou/s2i-java:latest"
  - "registry.access.redhat.com/jboss-eap-7/eap70-openshift:latest"
  - "registry.access.redhat.com/rhscl/mongodb-32-rhel7:latest"

### OpenShift Vars
repo_version: "3.3"
docker_version: "1.10.3"
docker_device: /dev/xvdb
idm: false
install_metrics: true
install_logging: true
#### Vars for the Ansible hosts file
master_api_port: 443
multi_tenant_setting: "os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'"
master_lb_dns: "master.{{subdomain_base}}"

cloudapps_suffix: 'cloudapps.{{subdomain_base}}'
openshift_master_ldap_ca_file: 'openshift_master_ldap_ca_file=/root/ca.crt'
osrelease: 3.3.1.7
openshift_master_overwrite_named_certificates: true



timeout: 60


### CLOUDFORMATIONS vars

project_tag: "{{config}}-{{guid}}"
zone_internal_dns: "internal.{{subdomain_base}}."
zone_public_dns: "{{subdomain_base}}."
cloudapps_dns: '*.cloudapps.{{subdomain_base}}.'

master_public_dns: "master.{{subdomain_base}}."
vpcid_cidr_block: "192.168.0.0/16"
vpcid_name_tag: "{{subdomain_base}}"

az_1_name: "{{ aws_region }}b"
az_2_name: "{{ aws_region }}c"

subnet_private_1_cidr_block: "192.168.2.0/24"
subnet_private_1_az: "{{ az_2_name }}"
subnet_private_1_name_tag: "{{subdomain_base}}-private"

subnet_private_2_cidr_block: "192.168.1.0/24"
subnet_private_2_az: "{{ az_1_name }}"
subnet_private_2_name_tag: "{{subdomain_base}}-private"

subnet_public_1_cidr_block: "192.168.10.0/24"
subnet_public_1_az: "{{ az_1_name }}"
subnet_public_1_name_tag: "{{subdomain_base}}-public"

subnet_public_2_cidr_block: "192.168.20.0/24"
subnet_public_2_az: "{{ az_2_name }}"
subnet_public_2_name_tag: "{{subdomain_base}}-public"

dopt_domain_name: "{{ aws_region }}.compute.internal"

rtb_public_name_tag: "{{subdomain_base}}-public"
rtb_private_name_tag: "{{subdomain_base}}-private"

nfs_instance_type: "t2.small"
bastion_instance_type: "t2.medium"
master_instance_type: "m4.xlarge"
infranode_instance_type: "m4.4xlarge"
node_instance_type: "m4.xlarge"
num_nodes: 24
key_name: "roadshow"

cf_template_description: "{{config}}-{{guid}} template "
