## TODO: What variables can we strip out of here to build complex variables?
## i.e. what can we add into group_vars as opposed to config_vars?
## Example: We don't really need "subdomain_base_short". If we want to use this,
## should just toss in group_vars/all.
### Also, we should probably just create a variable reference in the README.md
### For now, just tagging comments in line with configuration file.

###### VARIABLES YOU SHOULD CONFIGURE FOR YOUR DEPLOYEMNT
###### OR PASS as "-e" args to ansible-playbook command

### Route 53 Zone ID (AWS)
HostedZoneId:  Z186MFNM7DX4NF
admin_user: wkulhane-redhat.com
### Key Pair name created for EC2 instances (AWS)
key_name: "workshop_aws"

## Networking (AWS)
subdomain_base_short: "{{ guid }}"
subdomain_base_suffix: ".openshift.opentlc.com"
subdomain_base: "{{subdomain_base_short}}{{subdomain_base_suffix}}"

## Environment Sizing

bastion_instance_type: "t2.large"
# master_instance_type: "t2.large"
master_instance_type: "c4.xlarge"
etcd_instance_type: "{{master_instance_type}}"
nfs_instance_type: "c3.large"
infranode_instance_type: "m4.4xlarge"
node_instance_type: "m4.4xlarge"
node_instance_count: 4

###### VARIABLES YOU SHOULD ***NOT*** CONFIGURE FOR YOUR DEPLOYEMNT
###### You can, but you usually wouldn't need to.
ansible_ssh_user: ec2-user
remote_user: ec2-user

rhel_repos:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-ose-{{repo_version}}-rpms

use_subscription_manager: true
use_opentlc_repos: false

## NFS Server settings
nfs_vg: nfsvg
nfs_pvs: /dev/xvdb
nfs_export_path: /srv/nfs

nfs_shares:
  - nexus

## This might get removed
env_specific_shares:
  - jenkins

admin_project: "opentlc-shared"

user_vols: 200
user_vols_size: 5Gi

cache_images:
  - "registry.access.redhat.com/jboss-eap-7/eap70-openshift:latest"
  - "registry.access.redhat.com/openshift3/jenkins-2-rhel7:latest"
  - "registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7:latest"
  - "registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7:latest"
  - "registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7:latest"

## This might get removed
env_specific_images:
  - "openshiftdemos/gogs:latest"
  - "sonatype/nexus3:latest"

### OpenShift Vars
repo_version: "3.4"
docker_version: "1.12.5"
docker_device: /dev/xvdb
install_nfs: true
deploy_openshift: true
deploy_openshift_post: true
deploy_env_post: true
idm: true
install_metrics: true
install_logging: true

#### Vars for the Ansible hosts file
master_api_port: 443
multi_tenant_setting: "os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'"
master_lb_dns: "master.{{subdomain_base}}"

cloudapps_suffix: 'cloudapps.{{subdomain_base}}'
openshift_master_ldap_ca_file: 'openshift_master_ldap_ca_file=/root/ca.crt'
## TODO: This should be registered as a variable. Awk for os verions (OCP).
## yum info openshift...
osrelease: v3.4
openshift_master_overwrite_named_certificates: true
timeout: 60

### CLOUDFORMATIONS vars

project_tag: "{{ config_name }}-{{ guid }}"

create_internal_dns_entries: true
use_internal_dns_zone: true
zone_internal_dns: "{{subdomain_base}}.internal."
chomped_zone_internal_dns: "{{subdomain_base}}.internal"
zone_public_dns: "{{subdomain_base}}."
cloudapps_dns: '*.cloudapps.{{subdomain_base}}.'

master_public_dns: "master.{{subdomain_base}}."
bastion_public_dns: "bastion.{{subdomain_base}}."

vpcid_cidr_block: "192.168.0.0/16"
vpcid_name_tag: "{{subdomain_base}}"

az_1_name: "{{ aws_region }}a"
az_2_name: "{{ aws_region }}b"

subnet_private_1_cidr_block: "192.168.2.0/24"
subnet_private_1_az: "{{ az_2_name }}"
subnet_private_1_name_tag: "{{subdomain_base}}-private"

subnet_private_2_cidr_block: "192.168.1.0/24"
subnet_private_2_az: "{{ az_1_name }}"
subnet_private_2_name_tag: "{{subdomain_base}}-private"

subnet_public_1_cidr_block: "192.168.10.0/24"
subnet_public_1_az: "{{ az_1_name }}"
subnet_public_1_name_tag: "{{subdomain_base}}-public"

subnet_public_2_cidr_block: "192.168.20.0/24"
subnet_public_2_az: "{{ az_2_name }}"
subnet_public_2_name_tag: "{{subdomain_base}}-public"

dopt_domain_name: "{{ aws_region }}.compute.internal"

rtb_public_name_tag: "{{subdomain_base}}-public"
rtb_private_name_tag: "{{subdomain_base}}-private"

cf_template_description: "{{ config_name }}-{{ guid }} template "
