######################### Populate Dynamic Inventory

- name: Get Hosts from aws
  shell: ../ansible/scripts/cf-list-hosts.sh all {{config}}-{{guid}} {{aws_region}}
  register: group_hostnames
  failed_when: group_hostnames.stderr
  tags: [ dynamic_inventory, get_hosts ]

- name: Add Hosts
  add_host:
      name: "{{ item.split()[1] }}"
      public_hostname: "{{ item.split()[0] }}"
      private_hostname: "{{ item.split()[1] }}"
      availability_zone: "{{ item.split()[2] }}"
      groups: "allhosts,{{ item.split()[3] }}"
      ansible_ssh_user: "{{ansible_ssh_user}}"
      remote_user: "{{remote_user}}"
      ansible_ssh_private_key_file: "~/.ssh/{{key_name}}.pem"
  with_items: '{{group_hostnames.stdout_lines}}'
  tags: [ dynamic_inventory, populate_hosts ]

- name: generate ansible hosts file
  template: src=./files/inventory_templates/hosts.{{config}}.j2 dest=../workdir/hosts-{{config}}-{{guid}}
  tags: [ dynamic_inventory, generate_ansible_host_file ]
